### ISSUE TITLE
pdfviewer: saveAsBlob/download crashes when a stamp is on the last page

### ISSUE THREAD

**Issue by bort2012** [syncfusion/ej2-javascript-ui-controls#100]
when a pdf with many pages is loaded into the pdfviewer and there is a stamp on the last page. If I do not scroll down and call saveAsBlob or click the download button the backend crashes with the following message:
![image](https://user-images.githubusercontent.com/2348044/108898926-1a737900-7618-11eb-94b5-3b8cebfcc113.png)

Steps to reproduce:
- go to [https://ej2.syncfusion.com/demos/#/material/pdfviewer/default.html](https://ej2.syncfusion.com/demos/#/material/pdfviewer/default.html)
- scroll to the last page in the example pdf
- add a stamp
- download the pdf
- upload the downloaded pdf with the open button into the viewer
- now download it again but do not scroll down to the stamp
- see error

**Comment by bort2012** [comment]
are there any news?

**Comment by bort2012** [comment]
are there any news?

**Comment by bort2012** [comment]
I found out that this problem goes further:
If I place some other annotations on the last page they are not saved to the pdf in the second download but there is no error message of the service. E.g. free text annotation or an arrow.

Steps to reproduce:

* go to https://ej2.syncfusion.com/demos/#/material/pdfviewer/default.html
* scroll to the last page in the example pdf
* add some annotations like freetext, arrow, line and comment
* download the pdf
* upload the downloaded pdf with the open button into the viewer again
* now download it again but do not scroll down to the stamp before
* see no error
* open the downloaded pdf in a third-party viewer like adobe
* see there are no annotations on the last page

This problem is very critical for our customer because in his business process we need to open and save a pdf several times programaticly. But he does not always scroll to the end of the pdf. 
We use the load function and the saveAsBlob function but the behavior is the same as using the open button and the download button of the pdfviewer. So you can see the bahvior if you do the steps to reproduce.

**Comment by bort2012** [comment]
are there any news?

**Comment by DhivyaBharathi1307** [comment]
Hi bort2012,



We were able to reproduce the reported issue “Annotations are not saved properly in the PDF documents”. We will check and provide further details on February 7, 2022.



Regards,
Dhivya.

**Comment by syncsiva** [comment]
Closing for housekeeping purposes. Further, the reported bug can be tracked through below feedback link further,
https://www.syncfusion.com/feedback/32542
