### ISSUE TITLE
PivotView ignores parameters added in DataManager

### ISSUE THREAD

**Issue by pirras-torres** [syncfusion/ej2-javascript-ui-controls#101]
Please update ej2-javascript-ui-controls/controls/pivotview/src/pivotview/base/pivotview.ts  file in method in getData:

```
private getData(): void {
        if (isBlazor()) {
            (this.dataSourceSettings.dataSource as DataManager).
                executeQuery(new Query().requiresCount()).then(this.executeQuery.bind(this));
        } else {
            (this.dataSourceSettings.dataSource as DataManager).executeQuery(new Query()).then(this.executeQuery.bind(this));
        }
    }
```
    
    I need to use defaultQuery in DataManager because I add parameters and this method ignores my paramters because use new Query().
    
    Please verify if defaultQuery is not nul and use this value if not.

**Comment by RameshG2015** [comment]
Hi Pirras,
We have logged your requirement as a feature task in our data base. And it will be available at the end of April, 2021. Kindly track the task in the following link.
https://www.syncfusion.com/feedback/22777/provision-to-set-own-query-in-datamanager
We appreciate your patience until then.
Regards,
Ramesh G.

**Comment by maniram21** [comment]
Hi Pirras

We are glad to announce that our Essential Studio 2021 Volume 1 Release v19.1.0.54 is rolled out where the requested feature “Provision to set own query in datamanager” has been included and it is available for download under the following link.

https://www.syncfusion.com/forums/164043/essential-studio-2021-volume-1-release-v19-1-0-54-is-available-for-download

Now we consider "defaultQuery" property of DataManager where you can set your own filter to fetch the data. Kindly refer to the following sample,

https://stackblitz.com/edit/pfnzrw?file=index.js 

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Manikandan
