### ISSUE TITLE
Grouping broken after view and date change

### ISSUE THREAD

**Issue by duzenko** [syncfusion/ej2-javascript-ui-controls#107]
Please review the stackblitz demo
https://stackblitz.com/edit/angular-schedule-setting-dynamic-view-interval-waqj6t?file=app.component.ts

Steps:

1. Page loads. The default view is 'TimelineWeek' with a simple grouping. All good.
![image](https://user-images.githubusercontent.com/1481807/112651170-cea13300-8e54-11eb-8721-c367ab643c39.png)
2. Click the 'Week -> Day' button. The view changes to 'Day'. All good.
![image](https://user-images.githubusercontent.com/1481807/112651234-df51a900-8e54-11eb-8057-b7f1fa3b6827.png)
3. Click the 'Shift Date' button. The date shifts but the vertical hours layout breaks and the horizontal groups appear. Bad.
![image](https://user-images.githubusercontent.com/1481807/112651290-ed072e80-8e54-11eb-8d72-0f45838f51dd.png)

**Comment by Nevitha-Ravi** [comment]
Hi  duzenko ,

We have checked the shared sample and suggest to use **CurrentView** property instead of isSelected option in view settings. We have modified the shared sample which is working properly.
https://stackblitz.com/edit/angular-schedule-setting-dynamic-view-interval-2b3vtp?file=app.component.html 

  <ejs-schedule #scheduleObj width='100%' height='650px' [selectedDate]="selectedDate" [currentView]="currentView"
    [eventSettings]="eventSettings" [showHeaderBar]="false">
    <e-views>
      <e-view displayName='Day' option='Day'></e-view>
      <e-view displayName='Week' option='TimelineWeek' [group]="group" [timeScale]="timeScale">
      </e-view>
    </e-views>

  currentView: string = "TimelineWeek";

Please try the solution and let us know if you need any further assistance.

Regards,
Nevitha

**Comment by duzenko** [comment]
> 
> 
> Hi duzenko ,
> 
> We have checked the shared sample and suggest to use **CurrentView** property instead of isSelected option in view settings. We have modified the shared sample which is working properly.
> https://stackblitz.com/edit/angular-schedule-setting-dynamic-view-interval-2b3vtp?file=app.component.html
> 
> <ejs-schedule #scheduleObj width='100%' height='650px' [selectedDate]="selectedDate" [currentView]="currentView"
> [eventSettings]="eventSettings" [showHeaderBar]="false">
> 
> 
> <e-view displayName='Week' option='TimelineWeek' [group]="group" [timeScale]="timeScale">
> 
> currentView: string = "TimelineWeek";
> 
> Please try the solution and let us know if you need any further assistance.
> 
> Regards,
> Nevitha

Sorry, it's not possible for us due to [another](https://github.com/syncfusion/ej2-javascript-ui-controls/issues/88#issuecomment-723800790) bug in your control

**Comment by Hareesh22** [comment]
Hi Duzenko,

We have modified your shared sample based on your shared query “**_Grouping broken after view and date change without using currentView property_**” using **isSelected** option from the views property of the Scheduler, which can be viewed from the following link.

**Sample**: https://stackblitz.com/edit/angular-schedule-setting-dynamic-view-interval-as8iiy?file=app.component.ts 

>   toggleView() {
>     (this.scheduleObj.views[0] as any).isSelected = true;
>     (this.scheduleObj.views[1] as any).isSelected = false;
>     this.scheduleObj.refresh();
>   }

Kindly try the above solution and get back to us if you need any further assistance.

We will be happy to assist you..!

Regards,
Hareesh

**Comment by duzenko** [comment]
> 
> 
> Hi Duzenko,
> 
> We have modified your shared sample based on your shared query “**_Grouping broken after view and date change without using currentView property_**” using **isSelected** option from the views property of the Scheduler, which can be viewed from the following link.
> 
> **Sample**: https://stackblitz.com/edit/angular-schedule-setting-dynamic-view-interval-as8iiy?file=app.component.ts
> 
> > toggleView() {
> > (this.scheduleObj.views[0] as any).isSelected = true;
> > (this.scheduleObj.views[1] as any).isSelected = false;
> > this.scheduleObj.refresh();
> > }
> 
> Kindly try the above solution and get back to us if you need any further assistance.
> 
> We will be happy to assist you..!
> 
> Regards,
> Hareesh

Seems to work for us, thanks
