### ISSUE TITLE
Task Type change is not applied to taskdata

### ISSUE THREAD

**Issue by PaulMcManus23** [syncfusion/ej2-javascript-ui-controls#113]
https://github.com/syncfusion/ej2-javascript-ui-controls/blob/2807d50145199e32321f46d421a4a8d311552d25/controls/gantt/src/gantt/actions/edit.ts#L532

When I change the task type, it seems that the value on the taskdata object is not updated. Hence the resulting resource allocation changes are delayed somehow.

Why was this line commented out?

**Comment by MonishaSivanthilingam** [comment]
Hi PaulMcManus23,

Greetings from Syncfusion support.

We have analyzed your query, however, we were unable to replicate the issue you reported. The taskType is updated in the taskData after editing. In the save requestType in the actionComplete event, the taskData is updated with the updated taskType value. Please share more details about the issue you faced such as:
1.	The use cases in which you are facing this issue.
2.	The steps to be taken to replicate this issue.
3.	Please find the sample we used to validate your issue below.
Sample: https://stackblitz.com/edit/eiehoe?file=index.ts
If possible, please modify the sample to replicate your issue.
4.	Also, could you please share what you are trying to achieve, as it would help us in identifying the issue you reported.



 

As you can see in the screenshot above, the taskType has been updated in the taskData in the arguments of the actionComplete event.

Any information you could share with us will be useful to us in providing you with a solution.

Regards,
Monisha.
