### ISSUE TITLE
Gantt updateTaskId dependency error

### ISSUE THREAD

**Issue by thijs4ef** [syncfusion/ej2-javascript-ui-controls#114]
Hi,

I get an error after running the updateTaskId method in the gantt (in react):
The error: TypeError: pred is undefined
Details:
![image](https://user-images.githubusercontent.com/62025666/120613372-79862c80-c456-11eb-8666-c22688343b60.png)

It looks like the updatePredecessorOnUpdateId is always called in the updateTaskId method. [link to method](https://github.com/syncfusion/ej2-javascript-ui-controls/blob/e6620d7d78c80106165bbd7e22a032a42bd7fa17/controls/gantt/src/gantt/actions/edit.ts#L1896)

I forked one of the stackblitz examples and reproduced the error. [link to the fork](https://github.com/thijs4ef/gantt-updateTaskId-bug)

Maybe this issue can be fixed by applying the [the null check that is done on the parents](https://github.com/syncfusion/ej2-javascript-ui-controls/blob/e6620d7d78c80106165bbd7e22a032a42bd7fa17/controls/gantt/src/gantt/actions/edit.ts#L1883) on line 1896.

Thanks!

**Comment by MonishaSivanthilingam** [comment]
Hi thijs4ef,

Greetings from Syncfusion support.

We were able to replicate the issue you reported and have considered it as a bug from our side. We have logged a bug report for it. You can track its status from the below feedback link.

**Feedback:** https://www.syncfusion.com/feedback/25957/issue-when-using-updatetaskid-method-when-predecessor-field-is-not-mapped-in-the

The fix will be provided in the patch release scheduled for June 16, 2021.

We appreciate your patience until then.

Regards,
Monisha.

**Comment by MonishaSivanthilingam** [comment]
Hi thijs4ef,
 
Thank you for your patience.
 
The reported issue “[Issue when using updateTaskId method when predecessor field is not mapped in the taskfields](https://www.syncfusion.com/feedback/25957/issue-when-using-updatetaskid-method-when-predecessor-field-is-not-mapped-in-the)” has been resolved in version **v19.1.69**. Please find the release notes from the below link.
 
**Release Notes:** https://ej2.syncfusion.com/react/documentation/release-notes/19.1.69/?type=all#gantt
 
Please contact us if you require any further assistance.
 
Regards,
Monisha.
