### ISSUE TITLE
how can i guilp build ej2-base  success?i got a lot of erros 

### ISSUE THREAD

**Issue by CarlosCheniiii** [syncfusion/ej2-javascript-ui-controls#123]
![image](https://user-images.githubusercontent.com/52032043/133568988-0bf9e5f7-2267-4c57-a70c-23d462c8406b.png)
how can i solve it

**Comment by CarlosCheniiii** [comment]
![image](https://user-images.githubusercontent.com/52032043/133569564-9b81e322-13f8-4697-94dd-95f13b8d8b59.png)

my versions

**Comment by CarlosCheniiii** [comment]
@sujithvj

**Comment by CarlosCheniiii** [comment]
@gunasekar-kuppusamy

**Comment by Mydeen-SN** [comment]
Hi @CarlosCheniiii ,

We have resolved the issue. Can you check the compilation now?

**Comment by CarlosCheniiii** [comment]
hi @Mydeen-SN ,i try that,the ej2-javascript-ui is ok,but the ej2-angular-ui still has the errors,and also i want to ask that, it download the ej2-javascript-ui and open the ej2-base.the i run npm i and npm run build, they all successed and i got a lot of files like .js and .css，then what should i do to get the files like these 
![607617dd9124131e265d1622db91dae](https://user-images.githubusercontent.com/52032043/134444986-1d79124d-2f9a-4406-9306-81d22f7b628d.png)
and how to publish it

**Comment by Mydeen-SN** [comment]
Hi @CarlosCheniiii 

We have only included the ts to js compiler for this packages for now, we have not included the bundler to bundle the packages which we maintain internally for package bundling. If you face any issues in this packages please share it the issue details with us we will validate and resolve it from our end.

**Comment by syncsiva** [comment]
Close the issue since has not had any activity for 3 months.
