### ISSUE TITLE
merge cells has bug

### ISSUE THREAD

**Issue by jinges** [syncfusion/ej2-javascript-ui-controls#131]
![image](https://user-images.githubusercontent.com/4587360/147751974-2854a371-54db-4187-b354-09f4f8fb264a.png)
![image](https://user-images.githubusercontent.com/4587360/147752021-44f7bad0-1d10-4ba0-896a-193c3fb2a1a5.png)

**Comment by syncsiva** [comment]
@jinges Can you please share more details or component name?

**Comment by syncsiva** [comment]
This issue has not had any activity for 2 weeks. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
