### ISSUE TITLE
pdfviewer: signature form field cannot be dragged between pages 

### ISSUE THREAD

**Issue by SergenN** [syncfusion/ej2-javascript-ui-controls#143]
When creating a signature field it is not possible to drag them between pages in the PDF viewer (See GIF)
It is however still possible to place them on the page but you don't see the outline when you're dragging.

![Schermopname 2022-02-15 om 12](https://user-images.githubusercontent.com/6464764/154052496-e6bdceaf-6dbc-41b0-ba25-e5b5b6792f0a.gif)

**Comment by ShaminiKiruba** [comment]
Hi, 

Currently, there is no support to move the form fields from one page to another page in Syncfusion PDF Viewer and there are no immediate plans to implement this. At the planning stage for every release cycle, we review all open features. We will let you know when this feature is implemented. You can track the status of the implementation using the below feedback link. 

Feedback: https://www.syncfusion.com/feedback/32802/move-the-form-fields-from-one-page-to-another-page 

Regards,
Shamini
