### ISSUE TITLE
PdfViewer: When creating a signature field the background color is ignored.

### ISSUE THREAD

**Issue by SergenN** [syncfusion/ej2-javascript-ui-controls#147]
When creating a signature field by creating a custom drawing object the backgroundColor field is ignored while the settings in signatureIndicatorSettings work fine. It would be great for aesthetic purposes that the background color field is not ignored for signature fields. 

https://stackblitz.com/edit/angular-wf5rwu-gt6gvb?file=app.component.ts

I'm setting the drawtool like this: 
```typescript
addSignatureField(isInitial = false) {
    (this.pdfviewerControl.drawingObject as any) = {
      formFieldAnnotationType: 'SignatureField',
      name: 'Signature',
      color: '#bd0e0e',
      backgroundColor: 'rgba(000,000,000, .3)',
      isRequired: false,
      isPrint: true,
      tooltip: 'Test tooltip',
      font: {
        isItalic: false,
        isBold: false,
        isStrikeout: false,
        isUnderline: false,
      },
      isInitialField: isInitial,
      signatureIndicatorSettings: {
        text: 'Test indicator text',
        backgroundColor: 'rgba(000,000,000, .3)',
        color: '#bd0e0e',
      },
    };
    this.pdfviewerControl.tool = 'DrawTool';
  }
```

**Comment by DhivyaBharathi1307** [comment]
Hi Team,



On further analysis, we suspect that you have tried to add the signature field using the DrawingObject with the PDF Viewer instances. But Syncfusion PDF Viewer has used this property as private. So, we cannot access this property. We suggest you use the addFormField method as in the below Online demo to add the form fields.

However, currently, Syncfusion PDF Viewer does not have support to change the background color of the signature field. We have logged this as a feature and the feature implementation will be included in any of our upcoming releases. We do not have any immediate plans to implement this feature. We will let you know once the feature is implemented in our PDF Viewer. You can track the status using the below feedback link,


Feedback: [https://www.syncfusion.com/feedback/33319/need-to-provide-support-to-change-background-color-for-signature-field](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F33319%2Fneed-to-provide-support-to-change-background-color-for-signature-field&data=04%7C01%7Cdhivyabharathi.mohan%40syncfusion.com%7Ce04236d9c1a743d49cea08da02691a36%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637824947681509841%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cxIDEqmuZi4wS33eZvXGFmJgF2T%2BPYlZiXurXUEGfho%3D&reserved=0) 


Online demo for adding the form fields: https://ej2.syncfusion.com/angular/demos/#/bootstrap5/pdfviewer/form-designer


UG documentation for adding the form fields: https://ej2.syncfusion.com/angular/documentation/pdfviewer/form-designer/create-fillable-PDF-forms/create-programmatically/

https://ej2.syncfusion.com/angular/documentation/pdfviewer/form-designer/create-fillable-PDF-forms/create-with-user-interface-interaction/


Regards,
Dhivya.

**Comment by syncsiva** [comment]
This issue has not had any activity for a week. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
