### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by luigigubello** [syncfusion/ej2-javascript-ui-controls#157]
How can I report a vulnerability without disclosing it publicly in a GH issue?

Best,
Luigi

**Comment by TheveshwarJayakumar** [comment]
Hi Luigigubello,

Greetings from Syncfusion support
 
If the query is specific to Syncfusion components, you can share your query to our Syncfusion support system by creating support tickets. You can create the tickets by following the steps below.
 
1. Click on the following [link](https://www.bing.com/ck/a?!&&p=bf615392726a74e1JmltdHM9MTY1OTM0NDc4NyZpZ3VpZD1iY2ViMWEwNC02NTkzLTRmN2EtOTc5ZC05Mzc4OTUwZDAwMjQmaW5zaWQ9NTE0MQ&ptn=3&hsh=3&fclid=39747aa1-1179-11ed-b170-f78584feefdf&u=a1aHR0cHM6Ly93d3cuc3luY2Z1c2lvbi5jb20vYWNjb3VudC9sb2dpbg&ntb=1).
2. Login to our Syncfusion Bold Desk portal.
3. After logging in, you can have various options in our Dashboard in that navigate to support tab.
4. In the support tab, click on to New Ticket Creation option. While creating the ticket you can add your query related to our component.
 
For your convenience we have attached a following link which can help to solve your query.
 
Link:  https://opensource.stackexchange.com/questions/1958/report-a-security-issue-to-a-project-hosted-at-github
 
Please get back to us if you have any queries.
 
Regards,
Theveshwar

**Comment by luigigubello** [comment]
Hi @TheveshwarJayakumar 

> For your convenience we have attached a following link which can help to solve your query.

Unfortunately, Syncfusion doesn't have a security policy in the repository, or a `security.txt` on the website, and I am not able to find a public security policy on the website. Do you have a link for Synconfusion security policy?

> Login to our Syncfusion Bold Desk portal.

I would prefer not to create a new account for the Desk portal, just because I am not a Snyfusion customer, do you have a security e-mail? (e.g. `security@syncfusion.com` or something similar)

**Comment by TheveshwarJayakumar** [comment]
Hi Luigigubello,,

You can send a mail with the issue details to support@syncfusion.com. We will check and update you accordingly.

Regards,
Theveshwar

**Comment by syncsiva** [comment]
This issue has not had any activity for a month. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
