### ISSUE TITLE
visual picker

### ISSUE THREAD

**Issue by chensce** [syncfusion/ej2-javascript-ui-controls#158]
https://www.lightningdesignsystem.com/components/visual-picker/

**Comment by RagunathSF3421** [comment]
Hi @chensce,



Greetings from Syncfusion support.



As per the shared details, we are quite unclear about your exact requirement. Could you please explain more on your requirement? We suspect that you request a new component like you have shared in the link to be implemented by Syncfusion.



Regards,
Ragunath S

**Comment by syncsiva** [comment]
This issue has not had any activity for a month. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
