### ISSUE TITLE
web component support

### ISSUE THREAD

**Issue by chenshuichao** [syncfusion/ej2-javascript-ui-controls#159]
Are there any plan about web component？
As we know the web component spec v1.0 are supported by green browsers.

**Comment by Mydeensn** [comment]
@chenshuichao 

We don't currently have any immediate plans for supporting web components. However, we will take this into account for any upcoming releases. you may monitor the progress of this,  using the feedback link below.
https://www.syncfusion.com/feedback/39729/need-to-provide-support-for-web-components

**Comment by syncsiva** [comment]
Closing for housekeeping purposes. This feature can be tracked through below feedback link further,
https://www.syncfusion.com/feedback/39729/need-to-provide-support-for-web-components
