### ISSUE TITLE
CSS styles are not exported from the syncfusion packages

### ISSUE THREAD

**Issue by davidpanic** [syncfusion/ej2-javascript-ui-controls#160]
We have just updated our angular application to angular 15 which adds stricter scss rules. This means that we can no longer import syncfusion styles into our application due to the following error and similar ones for other styles:

```
./src/app/modules/calendar/containers/calendar-container/calendar-container.component.scss?ngResource - Error: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Package path ./styles/material.css is not exported from package /home/david/[redacted]/node_modules/@syncfusion/ej2-angular-schedule (see exports field in /home/david/[redacted]/node_modules/@syncfusion/ej2-angular-schedule/package.json)
```

**Comment by davidpanic** [comment]
This is a very simple fix, all that is required is to modify your package.json files to include the styles in the exports:

```json
{
  ...
  "exports": {
    ...,
    "./styles/": "./styles/"
  }
}
```

**Comment by Balaji-Elumalai** [comment]
@davidpanic - Thank you for contacting us.

We have validated the query. To avoid style compilation issues, map the **SCSS** styles in the **SCSS file path** `src/styles.scss` and add the `stylePreprocessorOptions` option under apps in the angular.json file.

`"styles": [
              "src/styles.scss"
            ],"stylePreprocessorOptions": {
     "includePaths": [
     "node_modules/@syncfusion"
    ]
  },`

Refer this [documentation](https://ej2.syncfusion.com/angular/documentation/getting-started/angular-cli/#adding-css-reference) and [sample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/angular152069461918.zip).

**Comment by syncsiva** [comment]
This issue has been resolved. Please feel free to reopen if you have any further queries.
