### ISSUE TITLE
CSS explicitly needs to be set as having side effects in order to work with Parcel.

### ISSUE THREAD

**Issue by LeoDog896** [syncfusion/ej2-javascript-ui-controls#161]
(From this [StackOverflow post](https://stackoverflow.com/a/75285951/7589775)):

Parcel [requires explicit declaration](https://github.com/parcel-bundler/parcel/issues/7825) of files that have side effects, including CSS:

```json
  "sideEffects": [
    "*.css"
  ],
```

**Comment by Mydeensn** [comment]
Hi @LeoDog896 


Thank you for bringing this issue to our attention. We're glad to hear that we were able to resolve the issue by changing the CSS import from the TSX file to .css. We appreciate your patience and understanding as we worked to resolve this issue. Please find the sample and CSS  reference attachment in below

 
![image](https://user-images.githubusercontent.com/92786290/219087563-a54385ca-c58e-4c5d-97ea-87e7971e4e21.png)

Sample: [parcel-spreadsheet.zip](https://github.com/syncfusion/ej2-javascript-ui-controls/files/10745270/parcel-spreadsheet.zip)

**Comment by dsibinski** [comment]
hi @Mydeensn ,
this is a workaround which indeed works. However, there's still a bug when importing these CSS from TSX file.
When will you include the `sideEffects` as @LeoDog896 suggested?

**Comment by TheveshwarJayakumar** [comment]
Hi All,

We have considered this as a bug at our end and we will plan to include this fix in any of our upcoming releases. You can the track the status of this fix in the below feedback link.

Feedback Link: https://www.syncfusion.com/feedback/41355/need-to-solve-the-issue-on-importing-css-from-tsx-file-in-parcel-framework-using

**Comment by syncsiva** [comment]
Closing for housekeeping purposes. Further, the reported bug can be tracked through below feedback link,
https://www.syncfusion.com/feedback/41355/need-to-solve-the-issue-on-importing-css-from-tsx-file-in-parcel-framework-using
