### ISSUE TITLE
My scheduler component crashes since resourceCollection can be empty

### ISSUE THREAD

**Issue by marc-wittwer** [syncfusion/ej2-javascript-ui-controls#162]
The name property cannot be accessed if the array is empty. This causes a crash in my application.

https://github.com/syncfusion/ej2-javascript-ui-controls/blob/ab669d9595fa7e6cb80c974eac627153dce3afc7/controls/schedule/src/schedule/event-renderer/event-base.ts#L607

To reproduce:
- This happened by adding events before adding resources using the CRUD api.

**Comment by vijayravi161099** [comment]
Hi Marc Wittwer,



We have checked your reported problem based on your shared details at our end and require additional details to proceed further. Can you share the below details to proceed further? It will help us to provide solution for your query earlier.


- Entire schedule related code snippets.
- Issue reproducing video demo.
- Detailed call stack error.
- Code snippets of how you are loading resource into the schedule.

Regards,
Vijay Ravi

**Comment by gsumankumar** [comment]
This issue has not had any activity for more than 1 week. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
