### ISSUE TITLE
Error alert when opening excel file 

### ISSUE THREAD

**Issue by rohitvishwakarma-sf** [syncfusion/ej2-javascript-ui-controls#169]
<img width="251" alt="Screenshot 2023-09-21 at 9 00 26 AM" src="https://github.com/syncfusion/ej2-javascript-ui-controls/assets/84082060/61620096-e6a1-47de-b9c4-0d7f7208b513">

I'm getting this error on opening excel file downloaded via excel-export library.
the error is there even if file has no content
I have also verified the xml content in an online validator by converting xlsx file to xml and its valid.
Please help!

**Comment by rajapandiravi1009** [comment]
Based on your query, we could see that you are facing the problem with opening the Excel file. Before we start providing solution to your query we need some more information for our clarification, so please share the below details that would be helpful for us to provide better solution.

1)             Share your exact requirement scenario with detailed description.

2)             Share the details about which Syncfusion component you are using in your application and how you are 
               exporting the Excel document.

3)             Share your complete code example, we would like to check your implementation.

4)             Share your Syncfusion package version.

5)             Share your error reproducing Excel file.

**Comment by rohitvishwakarma-sf** [comment]
The error was due to invalid timesheet name like . 
Excel have following validation rules for sheet name
- The name that you type does not exceed 31 characters.
- The name does not contain any of the following characters: :  \  /  ?  *  [  or  ].
- Name cannot be blank
and my timesheet name wasn't following these rules.


So this is not a syncfusion issue.
Thanks

**Comment by rohitvishwakarma-sf** [comment]
Just a suggestion 
can we add these rules to documentation as well @rajapandiravi1009
