### ISSUE TITLE
Firefox: no execCommand

### ISSUE THREAD

**Issue by johanneswilm** [syncfusion/ej2-javascript-ui-controls#171]
Hey,
Firefox stopped requiring disabling controls five years ago [1]. So you are now able to remove your last usages of `document.execCommand` for things like "enableInlineTableEditing" or "enableObjectResizing".

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1490641

**Comment by VinithaJeyakumar** [comment]
Hi johanneswilm,

Thanks for the update, we will validate and consider your suggestion as a future from our end.

Regards,
Vinitha

**Comment by gsumankumar** [comment]
Closing for housekeeping purposes. This feature can be tracked through below feedback link https://www.syncfusion.com/feedback/47758/need-to-remove-the-deprecated-method-document-execcommand-in-firefox-browser-from
