### ISSUE TITLE
this.lastPos scope is window and not TreeInterSectionObserver

### ISSUE THREAD

**Issue by csnyder8749** [syncfusion/ej2-javascript-ui-controls#173]
https://github.com/syncfusion/ej2-javascript-ui-controls/blob/4903766feac7995cad828c112467200e1d31f5db/controls/treegrid/src/treegrid/renderer/virtual-tree-content-render.ts#L614

**Comment by csnyder8749** [comment]
The clear method is being called out of scope.  

If this line was added to the constructor of the TreeInterSectionObserver class this would fix this issue.
**this.clear = this.clear.bind(this);**

e.g.
```
export class VirtualTreeContentRenderer extends VirtualContentRenderer {
    public getModelGenerator(): IModelGenerator<Column> {
        return new TreeVirtualRowModelGenerator(this.parent);
    }
    constructor(parent: IGrid, locator?: ServiceLocator) {
            super(parent, locator);
            this.addEventListener();
           
            //Suggest New Line of Code
            this.clear = this.clear.bind(this);
    }
    ........
```
    
    
This is the error being thrown everytime we scroll in a TreeGrid with virtualization:
Uncaught TypeError: Cannot set properties of undefined (setting 'lastPos')

**Comment by farveensulthana** [comment]
Hi Craig Snyder,



Greetings from Syncfusion support.



Before proceeding your query, we need some additional information to replicate the issue from our end. Kindly share the following details to proceed further.

1. Complete treegrid code details (properties and events, columns definition and events handling details if any).
2. Video demo/screenshot of the issue.
3. Share the platform that you are using with their version.
4.Share the package.json file to know about Syncfusion package version details.
5. Exact replication steps to replicate the issue from our end(using video Demo.
6. Are you using virtual with frozen columns or faced issue on enabling specific properties?
7. If possible, kindly replicate the issue from [this sample](https://stackblitz.com/edit/xphtix-rowccj?file=index.ts).


Kindly get back to us with the above details to proceed further.


Regards,

Farveen sulthana T

**Comment by gsumankumar** [comment]
This issue has been inactive for over a week, so we are closing it for housekeeping purposes. If you have any additional information to assist us, please reopen the issue. Thank you for your understanding.
