### ISSUE TITLE
Blazor support

### ISSUE THREAD

**Issue by fileman** [syncfusion/ej2-javascript-ui-controls#22]
Hi, have you evaluated or planned the release of a [blazor](https://github.com/aspnet/Blazor) compatible version of ej2?

**Comment by bharathm03** [comment]
@fileman Currently Blazor is an experimental project and [no public download is available](https://github.com/aspnet/Blazor/wiki/FAQ#q-how-can-i-try-out-blazor). We need to wait for its public release for evaluating and planning the compatibility for EJ2. 

-Bharath

**Comment by fileman** [comment]
Yes Blazor is experimental but I think near to preview release.
But .net standard could be useful because now razor ui view / pages can be contained in class library. 
Sorry it was more clear if split question in two separate issues

**Comment by bharathm03** [comment]
Yes we understand that it will be useful and combining with .net standard 2.0 will give it more power. However, we need more info on [JavaScript interop API](https://github.com/aspnet/Blazor/issues/37) and wrapper generation so that communication between Blazor and JavaScript libraries will be seamless. So we like to hold this until Blazor is available for public download. Thank you for your understanding

**Comment by fileman** [comment]
I've created #23 to separate the two aspect blazor & .netstandard support.
thanks

**Comment by bharathm03** [comment]
@fileman Sorry, I misunderstood both are the same request. Now I have updated our plan for .netstandard support in issue #23.

**Comment by danielmeza** [comment]
Now Blazor is public on nuget and there is a lot of documentation about JS Interop

**Comment by ptrepag** [comment]
Now that Server Side Blazor has been officially announced as part of Asp.Net Core 3, can we get support for syncfusion controls?

**Comment by fileman** [comment]
I hope that they release native control... With C# code base as in xamarin version

**Comment by vijays-git** [comment]
Thank you very much for your patience. 

We released our preview version of the Blazor components and it is available for download. Please see the link below.

[Blazor Components](https://www.syncfusion.com/blazor-components)
