### ISSUE TITLE
Filter Builder

### ISSUE THREAD

**Issue by bharathm03** [syncfusion/ej2-javascript-ui-controls#28]
Branched query from https://github.com/syncfusion/ej2/issues/6#issuecomment-402880149

A quick question. Devexpress have a fantastic control called Filter Builder. Which can be linked to the grid or used to create sql commands. This might be something you want to look at. You can see it here. We are Syncfusion devotees but are considering buying Devexpress just for this control. https://demos.devexpress.com/ASPxEditorsDemos/ASPxFilterControl/FilterBuilder.aspx

**Comment by Madhust** [comment]
@iang0ld Thank you for your feedback. Currently it is not available in our Essential JS 2 suite. We have logged your request for Filter builder control in our feature request list. 

For now, you can use the open-source Vue query builder to achieve your requirement. For your convenience, I have prepared a simple sample for using Vue query builder with our Grid component. Please find the sample from the below link.

**Sample:** https://github.com/SyncfusionSamples/ej2-vue-grid-vuequerybuilder

To run the sample, please use the following commands.

- npm install
- npm run dev

**Vue query builder:** https://dabernathy89.github.io/vue-query-builder/

**Grid documentation:** https://ej2.syncfusion.com/vue/documentation/grid/

**Comment by iang0ld** [comment]
This component is basic.  To be useful you would need to be able to generate the filters from a datasource definition (say a .net dataset) and generate sql for use with a remote datasource.  This jquery plug comes closer to achieving this.

https://querybuilder.js.org/index.html

**Comment by Madhust** [comment]
@iang0ld Thanks for your feedback. We have updated our feature description based on your suggestion.

**Comment by Sridhar-Narasimhan** [comment]
@iang0ld  We are happy to let you know that, we have rolled out the Query Builder component. I suggest you evaluate our Query Builder component's samples and documentations and share your feedback on this.

Samples : https://ej2.syncfusion.com/demos/#/material/query-builder/default.html 
Documentation: https://ej2.syncfusion.com/documentation/query-builder/getting-started/
