### ISSUE TITLE
Changing filter operator of FilterBar filter

### ISSUE THREAD

**Issue by egozavr** [syncfusion/ej2-javascript-ui-controls#29]
Hi! 

I use syncfusion grid in Angular app. Can you explain how to set filtering operator on column with `FilterBar` type filtering. Setting 
```typescript
gridFilterSettings: FilterSettingsModel = {
    type: 'FilterBar', mode: 'Immediate', immediateModeDelay: 500,
    columns: [
      { field: 'full_name', matchCase: false, operator: 'contains', predicate: 'and', value: '', },
    ]
  };
```
change only *initial* filtering for `full_name` column. I want to use `contains` operator, but it seems to be `startsWith`.

Thanks.

**Comment by gurupriyadharshini** [comment]
Hi egozavr,

 

Thanks for contacting Syncfusion support.

 

We have checked your query and if you want to set the filter operator for a particular column, then you can achieve your requirement by using ‘**actionBegin**’ event which will be triggered before any Grid actions such as filtering , paging etc. Please refer to the below code example, Documentation link and sample link. 

 [app.component.ts]
```
@Component({

  selector: 'app-root',

  template: `<ejs-grid [dataSource]='data' id="gridcomp"  allowPaging='true' allowFiltering='true'

  (actionBegin)= 'beforeFiltering($event)'>

<e-columns>

    <e-column field='OrderID' headerText='Order ID' width='120' textAlign='Right'></e-column>

    <e-column field='ShipCountry' headerText='Ship Country' visible='false' width='150'></e-column>                      .  .  .  .  .  .  .  .  .  .  .  .

</e-columns>

</ejs-grid>`,

  styleUrls: ['./app.component.css'],

  encapsulation: ViewEncapsulation.Emulated

})

export class AppComponent implements OnInit {

  public data: Object[];

 

  ngOnInit(): void {

    this.data = data;

  }

 

   beforeFiltering(args) {

   if (args.requestType === 'filtering' && args.currentFilteringColumn === "ShipCountry") {

     args.columns.forEach(col => {

       if (col.field == 'ShipCountry') {

         col.operator = "contains";        

       }

     });

   }

}

}
```

Documentation: https://ej2.syncfusion.com/angular/documentation/grid/api-grid.html?lang=typescript#actionbegin

 

Sample: http://www.syncfusion.com/downloads/support/directtrac/general/ze/contains_incident2006988686

 

Regards,

Gurupriyadharshini S.

**Comment by egozavr** [comment]
Thanks for your answer, the solution works! 

But I'm wondering is there a way to set filtering operator for a particular column "permanently" i.e. without action interception?

**Comment by thavasianand** [comment]
Hi egozavr,

We have already considered “Set filterbar operator for particular column in Grid” as a feature and logged report for the same. This will be available in any of our upcoming release. 

Please let me know if any concern. 

Regards,
Thavasianand S.

**Comment by vijays-git** [comment]
We have created the feature request on our feedback portal. Please follow the link below for further updates.

[Provide support to change filter operator in column level and also using dropdown UI for filter bar](https://www.syncfusion.com/feedback/6519/provide-support-to-change-filter-operator-in-column-level-and-also-using-dropdown-ui-for-filter-bar)
