### ISSUE TITLE
Missing canvas rendering option

### ISSUE THREAD

**Issue by Joooooooooogi** [syncfusion/ej2-javascript-ui-controls#42]
I've just noticed that the canvas rendering option on the chart component is dropped since upgrading to ej2. Unfortunately we have some massive data charts which are now lacking in performance. Are there any plans to reimplement the HTML canvas option?

Thanks and regards!

**Comment by dharanidharandharmasivam** [comment]
Hi Joooooooooogi,

We have analyzed your requirement. We would like to let you know that, in EJ2 Syncfusion chart we have achieved better performance in comparing with EJ1 chart component and EJ2 chart you can inject the required modules alone. Therefore, we haven’t given support for canvas rendering in EJ2. We didn’t have any immediate plans for providing canvas rendering support, however we will consider your requirement. Before that we would like to know the following details, which will be useful in further analysis in providing better solution with SVG rendering itself.

•	Number of points (data source length) used in chart.
•	Series type and number of series used.
•	What are the features you have used in chart?

You can check the performance of EJ2 chart from here. We will be waiting for you.

Thanks,
Dharani.

**Comment by Joooooooooogi** [comment]
Hey Dharani, thansks for your feedback. We are currently rendering 6 series with around 100k points. The major performance issues appear on chart interaction but also live updating the chart - showing crosslines, panning, zoom in and out. It's kind of unsmooth and delayed. We have tested other systens which are using canvas on high data rates, which are performing as expected.

**Comment by dharanidharandharmasivam** [comment]
Hi Joooooooooogi,

**Query 1: Canvas rendering**
Currently we do not have support to achieve your requirement for rendering chart in canvas mode, but we have logged a feature request on this and this will be available in any of our upcoming release. This can be tracked through our feedback portal below.

Link: https://www.syncfusion.com/feedback/5085  

Please cast your vote to make it count. We will prioritize the features every release based on the demands.

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal.

**Query 2: SVG performance with 6 series with around 100k points.**
We have considered SVG performance with 6 series around 100k points as improvement and this will be available for volume 2 main release 2019 which is expected to be rolled out in the month of June 2019. We appreciate your patience until then.

Thanks,
Dharani.

**Comment by sreharii** [comment]
Hi Joooooooooogi,

Sorry for the delay in response.

We have provided the canvas mode support for our chart control. We have also attached the sample for your reference. Please find the sample below.

Sample: https://stackblitz.com/edit/q5wawm?file=index.js

Regarding the performance for the series. We are working on this we will update the status once the improvement is rolled out.

Regards,
Srihari M
