### ISSUE TITLE
version issue for ej2-buttons

### ISSUE THREAD

**Issue by SupriyaSudhindra** [syncfusion/ej2-javascript-ui-controls#48]
while trying to do npm install for ej2, I am getting error for the latest version...even though i downgrade it to lower version...it is giving error...as ``No matching version found for @syncfusion/ej2-buttons@~17.1.50``...please suggest...

**Comment by vinoth-Kumar-S** [comment]
Hi SupriyaSudhindra,  

Good day to you.
  
We suspect that error occurs while building application with duplicate packages. So, we recommend you run the below command to remove the duplicate packages and re-run the application to resolve this issue.
  
> npm dedupe  
   
**Documentation link**: https://ej2.syncfusion.com/angular/documentation/common/how-to/update-npm-package/
    
Could you please check the above documentation to solve this issue? Please get back to us if you need any further assistance on this.  
   
Regards,  
Vinoth Kumar S
