### ISSUE TITLE
TreeGrid Aggregate does not work in IE

### ISSUE THREAD

**Issue by mayo589** [syncfusion/ej2-javascript-ui-controls#53]
TreeGrid aggregate is not working in IE at all - it show error: "Object.keys: argument is not an Object" 
It even does not work on official documentation in IE here (Preview tab): https://ej2.syncfusion.com/javascript/documentation/treegrid/aggregates/#child-aggregate

My IE version is 11.0.9600.19155
![Screenshot_1](https://user-images.githubusercontent.com/6273587/60571353-c3020480-9d73-11e9-9132-8a4442d33ea1.png)

**Comment by ManivannanPadmanaban** [comment]
Hi Marek,

Thanks for contacting syncfusion support.

**Query: TreeGrid aggregate is not working in IE at all - it show error: "Object.keys: argument is not an Object"** 

The above reported issue is already known issue and we have fixed it. And the same will be included in our next release volume 2 2019, which is expected to be rolled out in the mid of July 2019.

Till then, we appreciate your patience.

Regards,
Manivannan Padmanaban.

**Comment by mayo589** [comment]
I can confirm, that with version 17.2.40 the problem is fixed.

Thanks :) 👍
