### ISSUE TITLE
React Grid rendering error

### ISSUE THREAD

**Issue by Cyberspirit** [syncfusion/ej2-javascript-ui-controls#54]
./node_modules/@syncfusion/ej2-grids/src/grid/renderer/render.js
Attempted import error: 'blazorTemplates' is not exported from '@syncfusion/ej2-base'.

**Comment by jmfarook** [comment]
Hi Cyberspirit,

Thanks for contacting Syncfusion support,

Your reported issue is already fixed at our end. But currently,  We are glad to announce that our Essential Studio 2020 Volume 2 release v18.2.0.44  is rolled out and in this release. So please upgrade to this version to resolve the issue. It is available for download under the following link.

[vol 2](https://www.syncfusion.com/forums/155798/essential-studio-2020-volume-2-release-v18-2-0-44-is-available-for-download)

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.


Regards,
J Mohammed Farook
