### ISSUE TITLE
Recurrence editor crash when recurrence would generate invalid date

### ISSUE THREAD

**Issue by os1r1s110** [syncfusion/ej2-javascript-ui-controls#61]
When using the recurrence editor and calling `.getRecurrenceDates(new Date(), recurrenceRule, null, 1)`, it completely crashes if the passed `recurrenceRule` would end up with an invalid date.

For example, calling it like so:
`getRecurrenceDates(new Date(), 'FREQ=YEARLY;BYMONTHDAY=30;BYMONTH=2;INTERVAL=1', null, 1)` crashes the app as the date it would result in would be february 30th, which is invalid.

**Comment by os1r1s110** [comment]
After debugging, I found out that it seems to occur because it cannot compute any valid date, which causes it to never get out of the loop.

In fact, all loop exits in the `date-generator` seem to rely on the fact that at least one valid date will be found. In the case where it doesn't happen like for all "invalid dates", it will never get out of loop, and crash.

**Comment by vinithadevi** [comment]
Dear Customer,

Syncfusion Greetings.

We could reproduce the reported issue and logged the below bug report and fix will be included in our JS2 weekly release on November 12, 2019.

https://www.syncfusion.com/feedback/9674/recurrence-editor-crash-when-recurrence-would-generate-invalid-date 

Regards,
M.Vinitha devi

**Comment by os1r1s110** [comment]
Good to know  :)

**Comment by os1r1s110** [comment]
Has it been included in the release? I don't see it in the release notes, I guess I'll take a look at the code directly hehe

**Comment by rajendranr-5483** [comment]
HI @os1r1s110 ,

Generally, we inform you about fix with release details. Sorry to missed to follow-up with you.

The fix included with 2020 Volume 1 release itself. Could you please check and update if any other concerns?
