### ISSUE TITLE
 The component does not edit an event when I use the method: saveEvent (event). The component is being used from React.

### ISSUE THREAD

**Issue by oleyva93** [syncfusion/ej2-javascript-ui-controls#66]
This is my code in React:
--------------------------------------
let event={
             "Id": 1,
             "ScheduleBooking": {
                      "reason": {
                          "id": NumberInt("3"),
                          "name": "Cardiovascular"
                      },
                      "insurance": {
                          "id": NumberInt("101606"),
                          "name": "HEALTH NET - SENIORITY PLUS RUBY"
                       },                
                  ],
                "IsAllDay": false,
                "Recurrence": "FREQ=DAILY;INTERVAL=1;COUNT=3;",
                "StartTime": "2020-02-03T18:32:29.113Z",
                "OriginalDate": "2020-02-03T18:32:29.113Z",
                "EndTime": "2020-02-03T19:32:29.113Z",
                "Subject": "Cardiovascular",
                "Description": "HEALTH NET - SENIORITY PLUS RUBY",
                "Location": "1500 NW 89th Ct, Doral, FL 33172, USA"
 }
this.scheduleObj.saveEvent(event, "EditOcurrence");
-----------------------------------------------
And I don't update the event with any changes I make

**Comment by sellakumark** [comment]
Dear Customer,

Greetings from Syncfusion Support.

We have validated the shared codes at our end and we suspect that you are trying to edit the single occurrence from the recurrence series. To edit the single occurrence, we have to get the recurrence collection by making use of getCurrentViewEvents  and from that collection pick an event which we want to edit like below code snippet

let data = new DataManager(this.scheduleObj.getCurrentViewEvents()).executeLocal(new Query().where('RecurrenceID', 'equal', 3));
data[0].Subject = 'Edited';
this.scheduleObj.saveEvent(data[0], 'EditOccurrence');

For more reference please check the below links

Sample: https://stackblitz.com/edit/react-7qrfms-q1kcae?file=index.js
UG: https://ej2.syncfusion.com/react/documentation/schedule/crud-actions/#updating-using-saveevent-method
API: https://ej2.syncfusion.com/react/documentation/api/schedule/#getcurrentviewevents

Kindly check all the above and revert us for further assistance.

Regards,
Sellakumar K

**Comment by rajendranr-5483** [comment]
@oleyva93 ,

We are closing this thread now due to long pending. Please reopen this thread if you have any other concerns or requirements.

Regards,
Rajendran R.
