### ISSUE TITLE
CODE128C

### ISSUE THREAD

**Issue by salimaamirouchen** [syncfusion/ej2-javascript-ui-controls#71]

**Comment by gshyam93** [comment]
Hi Salimaamirouchen,

Please look into the online sample link of Code 128C below. Please let us know if you have any doubts in Code 128C barcode.

Sample link: https://ej2.syncfusion.com/javascript/demos/#/material/barcode/code128C.html

Regards,
Shyam G

**Comment by Sridhar-Narasimhan** [comment]
We have already provided a solution to this issue. So we will close this issue as a long-overdue.
