### ISSUE TITLE
Schedule: how to set "interval" dynamically?

### ISSUE THREAD

**Issue by real-artswan** [syncfusion/ej2-javascript-ui-controls#73]
Hello!
Changing "interval" input programmatically doesn't work. 
I tried to change bound property and tried to call setScheduleProperties({interval: newValue}) both ways don't work. Also I tried to call refresh() after changing it. 

Here is an example based on your demo https://stackblitz.com/edit/angular-2cup4f?file=app.component.ts click button below the schedule while you're in "2 Weeks" view - nothing happens.

Is it possible to do? What to do if I need to have multiple views with the same type but different intervals?

**Comment by Ravikumar-Venkatesan-M** [comment]
Dear Customer, 

Greetings from Syncfusion support. 

We have validated your shared sample and we suggest you kindly use the below codes to change the views property by dynamically. 

```
toggleInterval() { 
    (this.scheduleObj.views[1] as any).interval = (this.weekInterval + 1); 
    (this.scheduleObj.views[1] as any).displayName = (this.weekInterval + 1) + 'Weeks'; 
    this.scheduleObj.refresh(); 
  } 
```

Sample: https://stackblitz.com/edit/angular-schedule-setting-dynamic-view-interval-ncmwqc?file=app.component.ts 

Kindly try the above sample and get back to us If you would need any further assistance. 

Regards, 
Ravikumar Venkatesan

**Comment by duzenko** [comment]
Something is not right
You already have a binding for `interval` in html but still reset it manually in typescript
Why does the html binding not work?

**Comment by duzenko** [comment]
> 
> 
> Dear Customer,
> 
> Greetings from Syncfusion support.
> 
> We have validated your shared sample and we suggest you kindly use the below codes to change the views property by dynamically.
> 
> ```
> toggleInterval() { 
>     (this.scheduleObj.views[1] as any).interval = (this.weekInterval + 1); 
>     (this.scheduleObj.views[1] as any).displayName = (this.weekInterval + 1) + 'Weeks'; 
>     this.scheduleObj.refresh(); 
>   } 
> ```
> 
> Sample: https://stackblitz.com/edit/angular-schedule-setting-dynamic-view-interval-ncmwqc?file=app.component.ts
> 
> Kindly try the above sample and get back to us If you would need any further assistance.
> 
> Regards,
> Ravikumar Venkatesan

It does not work with `TimelineWeek`, too

**Comment by sellakumark** [comment]
@duzenko - We don't consider the `interval` property as two way binding in the angular scheduler component. So we manually update this `interval ` property as dynamically using the scheduler instance.

**Comment by duzenko** [comment]
This breaks the `[group]` binding on 'e-view` in the current version

**Comment by vinithadevi-murugan** [comment]
Hi @duzenko 

Thanks for your update.

We have validated the reported “**This breaks the [group] binding on 'e-view` in the current version**” and “**schedule.refresh breaks UI**” problems at our side by preparing a sample with latest version. But we did not face the mentioned issue. The sample was working fine. Please find the below sample for your reference.

Sample: https://stackblitz.com/edit/angular-schedule-setting-dynamic-view-interval-cp2dhl?file=app.component.ts 

Kindly try the above sample and if you still face the mentioned issue, could you please replicate your problem in above sample to serve you better.

Regards,
Vinitha

**Comment by duzenko** [comment]
The bug with the groups we're having might not be directly related to interval
I will open a new ticket. I suppose we can close this one for now.

**Comment by rajendranr-5483** [comment]
Thanks @duzenko .
