### ISSUE TITLE
Schedule: resize not handled

### ISSUE THREAD

**Issue by duzenko** [syncfusion/ej2-javascript-ui-controls#75]
It seems the schedule component can't always handle its resize, at least in `TimelineWeek` view.
Here's the reproduction demo
https://stackblitz.com/edit/angular-q7m4on-1ep3ga?file=app.component.html
You can see as you toggle the button the events in the grid lose their relative positions to time lines.

**Comment by duzenko** [comment]
![image](https://user-images.githubusercontent.com/1481807/80598543-34f9b780-8a32-11ea-8b4f-1381354815f4.png)
![image](https://user-images.githubusercontent.com/1481807/80598618-4e026880-8a32-11ea-8c92-94d0e5af4c06.png)

**Comment by VengateshManiraj** [comment]
Dear Customer,

Greetings from Syncfusion Support.

We have validated your reported issue that “Events are lost its position while resizing the schedule” and we suggest you please use the **refreshEvents** method to overcome this problem. Please refer to the below code snippet.

```
toggle() {
    this.wide = !this.wide;
    this.scheduleObj.refreshEvents();
  }
```

And the same, we have modified your shared sample which is available in the below link.

Sample: https://stackblitz.com/edit/angular-q7m4on-zkxzby?file=app.component.ts

Please check the above sample and get back to us if you need any further assistance.

Regards,
Vengatesh

**Comment by duzenko** [comment]
> 
> 
> Dear Customer,
> 
> Greetings from Syncfusion Support.
> 
> We have validated your reported issue that “Events are lost its position while resizing the schedule” and we suggest you please use the **refreshEvents** method to overcome this problem. Please refer to the below code snippet.
> 
> ```
> toggle() {
>     this.wide = !this.wide;
>     this.scheduleObj.refreshEvents();
>   }
> ```
> 
> And the same, we have modified your shared sample which is available in the below link.
> 
> Sample: https://stackblitz.com/edit/angular-q7m4on-zkxzby?file=app.component.ts
> 
> Please check the above sample and get back to us if you need any further assistance.
> 
> Regards,
> Vengatesh

No, sorry, this is not a good solution
The resize is caused by the app menu many levels away from the component with the scheduler
There's absolutely no way I can wire that menu events to ejs

**Comment by VengateshManiraj** [comment]
> > Dear Customer,
> > Greetings from Syncfusion Support.
> > We have validated your reported issue that “Events are lost its position while resizing the schedule” and we suggest you please use the **refreshEvents** method to overcome this problem. Please refer to the below code snippet.
> > ```
> > toggle() {
> >     this.wide = !this.wide;
> >     this.scheduleObj.refreshEvents();
> >   }
> > ```
> > 
> > 
> > And the same, we have modified your shared sample which is available in the below link.
> > Sample: https://stackblitz.com/edit/angular-q7m4on-zkxzby?file=app.component.ts
> > Please check the above sample and get back to us if you need any further assistance.
> > Regards,
> > Vengatesh
> 
> No, sorry, this is not a good solution
> The resize is caused by the app menu many levels away from the component with the scheduler
> There's absolutely no way I can wire that menu events to ejs

@duzenko Syncfusion Scheduler handles the window resizing functionality only. In your case, element’s dimension only resized. So we suggest you please use the **ResizeSensor** in **created** event to trigger the Scheduler’s dimension changed like the below code snippet.

```
onCreated(args) {
    let scheduleEle = document.querySelector(".e-schedule");
    new ResizeSensor(scheduleEle, function() {
      let schObj = (scheduleEle as EJ2Instance).ej2_instances[0];
      (schObj as ScheduleComponent).refreshEvents();
    });
  }
```

For more reference please check the below sample.

Sample: https://stackblitz.com/edit/angular-q7m4on-zkxzby?file=app.component.ts

**Comment by duzenko** [comment]
> 
> 
> > > Dear Customer,
> > > Greetings from Syncfusion Support.
> > > We have validated your reported issue that “Events are lost its position while resizing the schedule” and we suggest you please use the **refreshEvents** method to overcome this problem. Please refer to the below code snippet.
> > > ```
> > > toggle() {
> > >     this.wide = !this.wide;
> > >     this.scheduleObj.refreshEvents();
> > >   }
> > > ```
> > > 
> > > 
> > > And the same, we have modified your shared sample which is available in the below link.
> > > Sample: https://stackblitz.com/edit/angular-q7m4on-zkxzby?file=app.component.ts
> > > Please check the above sample and get back to us if you need any further assistance.
> > > Regards,
> > > Vengatesh
> > 
> > 
> > No, sorry, this is not a good solution
> > The resize is caused by the app menu many levels away from the component with the scheduler
> > There's absolutely no way I can wire that menu events to ejs
> 
> @duzenko Syncfusion Scheduler handles the window resizing functionality only. In your case, element’s dimension only resized. So we suggest you please use the **ResizeSensor** in **created** event to trigger the Scheduler’s dimension changed like the below code snippet.
> 
> ```
> onCreated(args) {
>     let scheduleEle = document.querySelector(".e-schedule");
>     new ResizeSensor(scheduleEle, function() {
>       let schObj = (scheduleEle as EJ2Instance).ej2_instances[0];
>       (schObj as ScheduleComponent).refreshEvents();
>     });
>   }
> ```
> 
> For more reference please check the below sample.
> 
> Sample: https://stackblitz.com/edit/angular-q7m4on-zkxzby?file=app.component.ts

That half-works
Even though the events refresh the component itself does not resize back
Note the scroll bar on the 3rd screenshot

![image](https://user-images.githubusercontent.com/1481807/81676758-fb28a800-9458-11ea-8e9f-73d4e1a2d99d.png)
![image](https://user-images.githubusercontent.com/1481807/81676792-0aa7f100-9459-11ea-8569-ec10ae7062be.png)
![image](https://user-images.githubusercontent.com/1481807/81676845-198ea380-9459-11ea-99c7-bcd362fa27ca.png)

**Comment by VengateshManiraj** [comment]
@duzenko Sorry for the delay. We have modified the sample. Please check the below sample and get back to us if you need any further assistance. 
https://stackblitz.com/edit/angular-q7m4on-qtdqhd?file=app.component.html

**Comment by duzenko** [comment]
> 
> 
> @duzenko Sorry for the delay. We have modified the sample. Please check the below sample and get back to us if you need any further assistance.
> https://stackblitz.com/edit/angular-q7m4on-qtdqhd?file=app.component.html

Again, the `toggle()` function is just to simulate the real world case
Please don't put any code there

**Comment by VengateshManiraj** [comment]
> > @duzenko Sorry for the delay. We have modified the sample. Please check the below sample and get back to us if you need any further assistance.
> > https://stackblitz.com/edit/angular-q7m4on-qtdqhd?file=app.component.html
> 
> Again, the `toggle()` function is just to simulate the real world case
> Please don't put any code there

Modified the sample
https://stackblitz.com/edit/angular-q7m4on-4gtekh?file=app.component.ts

**Comment by duzenko** [comment]
```
  onCreated(args) {
    new ResizeSensor(this.scheduleObj.element, () =>{
      this.scheduleObj.showSpinner();
    this.scheduleObj.element
      .querySelectorAll("col")
      .forEach(e => e.removeAttribute("style"));
      this.scheduleObj.refreshEvents()}
    );
  }
```
