### ISSUE TITLE
Grid Excel filter type omitting lots of distinct values

### ISSUE THREAD

**Issue by leniel** [syncfusion/ej2-javascript-ui-controls#78]
Hello,

We're using the latest version of the JS library which is [18.1.59](https://ej2.syncfusion.com/documentation/release-notes/18.1.59/?type=all) as of now. I also tested with previous versions but the problem persists. The JS file being used is the full bundle one `ej2.min.js` that resides inside the dist folder.

The problem: the grid in question has almost 65000 rows and for the **Client** column the Excel type filter is missing a lot of distinct values. It only shows 19 values but there are many more...

![image](https://user-images.githubusercontent.com/764854/86251457-45402700-bb88-11ea-9cd5-b460a27418d2.png)

Note that the values are present in the data source because if the user types a value in the filter Search box, the check box with the missing value shows up.

![image](https://user-images.githubusercontent.com/764854/86252434-97357c80-bb89-11ea-874e-7bfbe0f4a54b.png)

We were previously using [this version](https://drive.google.com/file/d/1tYcVwHtlJscdKSnrKLB-lKvFQrJJgBL0/view?usp=sharing) of the library which I really don't know what is because the minified version has no information about the version. With this old version all the distinct values appear correclty for the Client filter. However we can't use this old library because it breaks when enabling the grid persistence feature.

This is how the grid is instantiated:

```JavaScript
let gridParams = {
            allowSorting: true,
            allowPaging: true,
            allowExcelExport: true,
            allowPdfExport: true,
            allowTextWrap: true,
            allowResizing: true,
            allowReordering: true,
            allowFiltering: true,
            filterSettings: { type: 'Excel', operator: 'contains', ignoreAccent: true, matchCase: false },
            showColumnChooser: true,
            editSettings: { allowEditing: false, allowAdding: false, allowDeleting: true, mode: 'Normal' },
            selectionSettings: { type: 'Multiple', enableSimpleMultiRowSelection: true },
            toolbar: toolbar,
            toolbarClick: toolbarClickHandler,
            dataSource: data,
            columns: columns,
            enablePersistence: true
}

let grid = new ej.grids.Grid(gridParams);

$(grid.element).removeClass('e-responsive');
$grid.html('');
grid.appendTo('#' + gridID);

window.grid = grid;
```

I hope anyone can shed some light regarding why the grid Excel filter is missing so many distinct values in the filter although the values are there...

**Comment by jmfarook** [comment]
Hi Leniel ,

Greetings from Syncfusion support.

From validating your query, we understand that you want to display all the distinct values at Excel filtering. By default, Excel-filter takes first 1000 value from the Grid dataSource and display the distinct value of first 1000 values. The remaining values are loaded based on your searching in the Excel-Filter(we have used the behavior for improving the performance of Excel-Filter rendering).

But, you can customize the display value count in the following way.


To achieve your requirement we suggest you change the filterchoicecount with dataSource length in Grid’s actionBegin event with requestType as ‘filterchoicerequest’. Please refer to the below code example and sample for your reference.

[Code example]

```
`actionBegin: function (args) {
    if (args.requestType == 'filterchoicerequest') {
      var dataCount = this.dataSource.length  //display your custom count ,  here we have displayed all values of your data source
      args.filterChoiceCount = dataCount;
    }
  },
`
```

[sample](https://stackblitz.com/edit/grid-123?file=index.js)

Please get back to us if you need further assistance.

Regards,
J Mohammed Farook
