### ISSUE TITLE
Uncaught TypeError in PivotView on horizontal scrolling on Firefox

### ISSUE THREAD

**Issue by florent-izypay** [syncfusion/ej2-javascript-ui-controls#83]
Following error is triggered on HorizontalScroll in a PivotView executed on Firefox v79.0

> Uncaught TypeError: mCont.querySelector(...).style.transform.split(...)[1] is undefined

https://github.com/syncfusion/ej2-javascript-ui-controls/blob/338e7ecee4a3e4a8f314a6429afe8e50ea394bbd/controls/pivotview/src/pivotview/actions/virtualscroll.ts#L280

The reason is quite simple, the previous line of code expects CSS property to be `transform: translate(<x>, <y>)` however, Firefox shortens `translate(<x>, <y>)` to `translate(<x>)` if `y=0`

Testing existance of `y` value (at index 1 of split() result) resolves the issue.

Please review PR #82

**Comment by RameshG2015** [comment]
Hi Florent,

We can face the issue in latest version (v79) of Firefox. So, we considered – “Issue on horizontal scrolling in Firefox” as a bug and logged a defect report in our data base. And, the fix will be available in our weekly patch release which is estimated to be rolled out on 1st September, 2020. You can track the task in the following link.

https://www.syncfusion.com/feedback/16899/

We appreciate your patience until then.

Regards,
Ramesh G.

**Comment by florent-izypay** [comment]
Resolved https://www.syncfusion.com/feedback/16899/horizontal-scrolling-issue-in-latest-version-of-firefox
