### ISSUE TITLE
SassError: SassError: Top-level selectors may not contain the parent selector "&".

### ISSUE THREAD

**Issue by walterdeboer** [syncfusion/ej2-javascript-ui-controls#84]
https://github.com/syncfusion/ej2-javascript-ui-controls/blob/7b06bdcdb1ca7c40fc7fa1f4ae398df737e66218/controls/inputs/styles/color-picker/_theme.scss#L122

https://github.com/syncfusion/ej2-javascript-ui-controls/blob/7b06bdcdb1ca7c40fc7fa1f4ae398df737e66218/controls/buttons/styles/switch/_layout.scss#L219

these lines results in the followin errors when running serving out Angular 9 app:

**ERROR in ./src/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--13-1!./node_modules/postcss-loader/src??embedded
!./node_modules/sass-loader/dist/cjs.js??ref--13-3!./src/styles.scss)
SassError: SassError: Top-level selectors may not contain the parent selector "&".**

N.B. we're customizing the syncfusion SCSS from the node_modules folder, using our own custom variables. I've also tried the SCSS downloaded from the theme studio, but it gives similar errors. With Angular 8 all worked fine, but with Angular 9 the errors  show up.

**Comment by walterdeboer** [comment]
See also: https://www.syncfusion.com/forums/152447/sass-top-level-selectors-may-not-contain-the-parent-selector

**Comment by Mydeen-SN** [comment]
Hi All, 
 
We are glad to announce that our Essential Studio 2020 Volume 3 release v18.3.0.35  is rolled out and is available for download under the following link. 
 
https://www.syncfusion.com/forums/158306/essential-studio-2020-volume-3-release-v18-3-0-35-is-available-for-download 
  
We have included the "Support both SASS and NodeSASS" with thi release. We thank you for your support and appreciate your patience in waiting for this release.  
  
Please get in touch with us if you would require any further assistance. 

Regards,
Mydeen S N
