### ISSUE TITLE
Schedule.refresh() breaks UI

### ISSUE THREAD

**Issue by duzenko** [syncfusion/ej2-javascript-ui-controls#88]
We have implemented dynamic `interval` switching based on your [suggestion](https://github.com/syncfusion/ej2-javascript-ui-controls/issues/73) but just noticed a quite ugly side-effect

Open the demo app here: https://stackblitz.com/edit/angular-2cup4f-bls9vl?file=app.component.html
Using the integrated header control: no problem switching between views. It just works.
Using an external `select` control on the top
- switch from Week to Crews - ok
- switch back from Crews to Week - the view is broken
We can't use the integrated header bar in our production because we need customized controls here.
![image](https://user-images.githubusercontent.com/1481807/98272628-fa04ad80-1f99-11eb-8355-93cce615eda7.png)
![image](https://user-images.githubusercontent.com/1481807/98272697-0983f680-1f9a-11eb-9c3d-04068e2069bb.png)

**Comment by Hareesh22** [comment]
Dear Customer,

Greetings form Syncfusion Support..!

We have validated your shared sample at our end and in that you have rendered two “Week” views but has different intervals. So you can’t switch between the same view programmatically using currentView property and for that, we have modified your shared sample using the **isSelected** field of the **views** property which can be viewed form the following link.

**Sample**: https://stackblitz.com/edit/angular-different-view-cusotmer-sharedlink?file=app.component.ts 

>   switchSchedulerView() {
    switch (this.currentSchedulerView) {
      case "day":
        this.scheduleObj.currentView = "Day";
        break;
      case "week":
        (this.scheduleObj.views[1] as ViewsModel).isSelected = true;
        (this.scheduleObj.views[2] as ViewsModel).isSelected = false;
        this.scheduleObj.refresh();
        break;
      case "2week":
        (this.scheduleObj.views[2] as ViewsModel).isSelected = true;
        (this.scheduleObj.views[1] as ViewsModel).isSelected = false;
        this.scheduleObj.refresh();
        break;
      case "crews-week":
        this.scheduleObj.currentView = "TimelineWeek";
        break;
    }
  }


> <e-views>
                <e-view displayName='1D' option='Day'></e-view>
                <e-view displayName='1W' [isSelected]="isSelectedWeek" option='Week'></e-view>
                <e-view displayName='2W' [isSelected]="isSelectedWeekInterval" option='Week' [interval]='2'></e-view>
                <e-view displayName='TW+G' option='TimelineWeek' [group]="group" [timeScale]='timeScale'>
                </e-view>
</e-views>

**UG**:
https://ej2.syncfusion.com/angular/documentation/schedule/views/#view-specific-configuration 
https://ej2.syncfusion.com/angular/documentation/schedule/views/#extending-view-intervals 

Kindly try the above solution and get back to us if you need any further assistance.

Regards,
Hareesh

**Comment by duzenko** [comment]
@Hareesh22 
Thanks for the reply

Actually, in production we only have one 'Week' view - sorry about that, Note that we need to switch the interval based on the view, so I edited the demo accordingly.
Please review it here: https://stackblitz.com/edit/angular-2cup4f-ryepz8?file=app.component.ts
Again, go from Week to Crews and back and observer the broken layout

**Comment by Hareesh22** [comment]
Dear Customer,

Thanks for the update.

We have modified our previously updated sample based on your reported problem using **isSelected** option of the views property of the Scheduler which can be viewed from the following link.

**Sample**: https://stackblitz.com/edit/angular-sample-scheduler-view-customized?file=app.component.ts 
**API link**: https://ej2.syncfusion.com/angular/documentation/api/schedule/viewsModel/#isselected 

>   switchSchedulerView() {
    switch (this.currentSchedulerView) {
      case "day":
        this.scheduleObj.currentView = "Day";
        break;
      **case "week":
        this.scheduleObj.views[1].isSelected = true;
        (this.scheduleObj.views[1] as ViewsModel).interval = 1;
        this.scheduleObj.refresh();
        break;
      case "2week":
        this.scheduleObj.views[1].isSelected = true;
        (this.scheduleObj.views[1] as ViewsModel).interval = 2;
        this.scheduleObj.refresh();
        break;**
      case "crews-week":
        this.scheduleObj.currentView = "TimelineWeek";
        break;
    }
  }

Kindly try the above solution and get back to us if you need any further assistance.

Regards,
Hareesh
