### ISSUE TITLE
diagrams breaking changes in 18.2.48

### ISSUE THREAD

**Issue by carlos-montiers** [syncfusion/ej2-javascript-ui-controls#89]
Hello my working code of a diagram editor that uses native shapes (svg) stop working since version 18.2.48. Works okay in version 18.2.46.

When I drag the icon from the palette to the diagram space an error ocurr. In console appears:

```
ERROR RangeError: Maximum call stack size exceeded
    at getContent (vendor.js:285207)
    at DiagramHtmlElement.set content [as content] (vendor.js:275136)
```

I did some research about the code that seems to cause the problem and seems is this portion of code added in version 18.2.48:
file: controls/diagrams/src/diagram/utility/dom-util.ts
```
+            let svgContent: string;
+            let div: SVGSVGElement = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
+            document.body.appendChild(div);
+            /* tslint:disable */
+            div.innerHTML = ((node.shape as any).content) as string ;            
+            /* tslint:disable */
+            svgContent = (div.getElementsByTagName('svg').length > 0)
+            ? div.getElementsByTagName('svg')[0].outerHTML : div.getElementsByTagName('g')[0].outerHTML;
+            /* tslint:disable */
+            (node.shape as any).content = svgContent;            
+            /* tslint:disable */
+            element.content = svgContent;
+            div.parentElement.removeChild(div);
```

I hope please you fix this issue if is a bug to allow me update my editor to use the last version of the library.

Sincerely, Carlos.

**Comment by aravindravi5230** [comment]
Hi Carlos,

We are unable to reproduce the reported issue at our end. We have created a sample to render native nodes in the palette. When we drag and drop the nodes from the palette, the node has been dropped properly in the diagram without any exception. We have attached a sample for your reference 

Sample: https://stackblitz.com/edit/gm7ga6

So please share with us more details of your issue i.e. what type of SVG content you used for the node which causes an exception when drop-in diagram or modify the above sample replicating an issue. This would help us to serve you better.

Regards
Aravind Ravi

**Comment by cmontiers-catena** [comment]
Hello Aravin

Many thanks for reply.

I did more research and now I found the cause: is using svg with annotations with template.

In your stackblitz code please try replace:

`obj.annotations = [{ style: { color: "white", fill: "transparent" } }];`

with:

`obj.annotations = [{ style: { color: "white", fill: "transparent" }, template: '<span class="badge">' + 1 + '</span>' }];`

After it, when you drag a svg icon to the diagram space you will get the error: Maximum call stack size exceeded.

If you try in package.json with:
"@syncfusion/ej2-diagrams": "18.2.46",

The error not happen.

**Comment by carlos-montiers** [comment]
Hello Aravin

Many thanks for reply.

I did more research and now I found the cause: is using svg with annotations with template.

In your stackblitz code please try replace:

`obj.annotations = [{ style: { color: "white", fill: "transparent" } }];`

with:

`obj.annotations = [{ style: { color: "white", fill: "transparent" }, template: '<span class="badge">' + 1 + '</span>' }];`

After it, when you drag a svg icon to the diagram space you will get the error: Maximum call stack size exceeded.

If you try in package.json with:
"@syncfusion/ej2-diagrams": "18.2.46",

The error not happen.

**Comment by aravindravi5230** [comment]
Hi Carlos,
   
Reported Issue: Exception occurs when drag and drop the SVG node into a diagram 
     
We can reproduce the issue and confirmed this as a defect. We have logged a defect report for this issue. We will fix this issue and provide the patch on the December 8th, 2020 weekly patch release.   
 
https://www.syncfusion.com/feedback/19920/exception-occurs-when-drag-and-drop-the-svg-node-into-diagram   
   
Regards,   
Aravind Ravi

**Comment by aravindravi5230** [comment]
Hi Carlos,   
 
We have fixed the reported issue and included it in our patch release (**v18.3.52**) which is rolled out successfully.      
      
Please upgrade to the latest version packages to resolve this issue.            
https://www.npmjs.com/package/@syncfusion/ej2-diagrams             
     
Regards,     
Aravind Ravi

**Comment by cmontiers-catena** [comment]
Hello Aravind,

Now works like a charm !

Many thanks,
Carlos

**Comment by carlos-montiers** [comment]
Hello Aravind,

Now works like a charm !

Many thanks,
Carlos
