### ISSUE TITLE
Minor clearing bug for drop downs not clearing all values

### ISSUE THREAD

**Issue by hermbo** [syncfusion/ej2-javascript-ui-controls#94]
Selected values are not fully clearing if a user chooses two options in different search events.

### Reproduce
- Open dropdown and search a term, choose an option
- Close the dropdown
- Open dropdown and search a another term, choose an option
- Try clearing the values using the x

### Screenshots
![select-dropdown-bug](https://user-images.githubusercontent.com/38641518/104501677-e88ce280-5594-11eb-881f-5a50eb5ba4f7.gif)

**Comment by SevvandhiN** [comment]
Hi Hermbo, 


Greetings from Synfusion support.


 
We checked your query. We are unable to reproduce the reported issue in our end with both remote and local data. Please find the sample on below with latest version (18.4.34.).
  
 
Sample : https://stackblitz.com/edit/qjbp5e-3dvjhy?file=index.js 

 
Please share the below details to proceed further.

1.	Share your current version details & code snippet.
2.	Have you made any customization in your application end. 
3.	If possible, please revert us with issue reproducing sample.  


Regards, 
Sevvandhi N

**Comment by hermbo** [comment]
Interesting, yes I see it working with your example. I am using the newest version as well, I'll see if I can do more digging maybe it's something in my code.
