### ISSUE TITLE
pdfviewer: existing stamp author gets overwritten on load with other user

### ISSUE THREAD

**Issue by bort2012** [syncfusion/ej2-javascript-ui-controls#95]
I have set the annotation author like this:
`this.pdfviewerControl.annotationSettings.author = this.settingsService.userName;`

When a new stamp is added the userName gets set to the stamp annotation and the dynamic text of the stamp.
But when I open this pdf with an other user the stamp annotation author of the existing stamp annotations gets overwritten with the new user. Other annotation types authors stay the origin userName as expected.

**Comment by bort2012** [comment]
are there any news?

**Comment by DhivyaBharathi1307** [comment]
Hi Team,

We have resolved the reported issue in the latest version v19.4.0.48. We have shared the sample in the latest version. 

Sample: https://stackblitz.com/edit/nu4mzu-cwqtj3?file=index.ts 

Please revert to us, if you need further assistance.

Regards,
Dhivya.

**Comment by syncsiva** [comment]
This issue has not had any activity for 2 weeks. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
