### ISSUE TITLE
pdfviewer: annotationAdd event not fired with custom stamp

### ISSUE THREAD

**Issue by bort2012** [syncfusion/ej2-javascript-ui-controls#99]
When a custom stamp is added with the button "Custom Stamp" then the annotationAdd event gets fired.
But when adding a custom stamp that was added to the menu programmatic it is not fired. I have added the programmatic stamp to the menu like this:
`this.pdfviewerControl.customStampSettings.customStamps = [{ customStampName: "Signature", customStampImageSource: this.settingsService.signatureBase64 }];`

**Comment by bort2012** [comment]
are there any news?

**Comment by Vasugisivajothi** [comment]
Hi Team, 
 
We were unable to reproduce the reported issue in our latest version 18.4.0.43. We have shared the sample in which we have tried to reproduce the issue. Please refer to the below sample,  
 
Sample: https://stackblitz.com/edit/nhkwvs?file=package.json 
 
 
Kindly try this and revert to us with more details if you have any concerns about this.  
 
 
Regards, 
Vasugi

**Comment by bort2012** [comment]
Hi thanks for trying to reproduce it.

I have checked your example. And I have noticed that the problem occurs only when added the stamp to the custom stamp menu.

I have changed your example to see the problem:
[https://stackblitz.com/edit/nhkwvs-1c8fch?file=index.ts](https://stackblitz.com/edit/nhkwvs-1c8fch?file=index.ts)

Regards,
Reiner

**Comment by DhivyaBharathi1307** [comment]
Hi Team,

We were able to reproduce the reported issue with the provided sample. However, we have resolved the reported issue in the latest version v19.4.0.48. We have shared the sample in the latest version. 

Sample: https://stackblitz.com/edit/nu4mzu-cwqtj3?file=index.ts 


Please revert to us, if you need further assistance.

Regards,
Dhivya.

**Comment by syncsiva** [comment]
This issue has not had any activity for 2 weeks. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
